package net.sourceforge.mochadoom.data;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import net.sourceforge.mochadoom.wad.CacheableDoomObject;

/**
 * LineSeg, generated by splitting LineDefs
 * using partition lines selected by BSP builder.
 * MAES: this is the ON-DISK structure. The corresponding memory structure,
 * segs_t, has fixed_t members.
 */

public class mapseg_t implements CacheableDoomObject {

    public mapseg_t() {

    }

    public char v1;
    public char v2;
    public char angle;
    public char linedef;
    public char side;
    public char offset;

    public static int sizeOf() {
        return 12;
    }

    @Override
    public void unpack(ByteBuffer buf)
            throws IOException {
        buf.order(ByteOrder.LITTLE_ENDIAN);
        this.v1 = buf.getChar();
        this.v2 = buf.getChar();
        this.angle = buf.getChar();
        this.linedef = buf.getChar();
        this.side = buf.getChar();
        this.offset = buf.getChar();

    }

};
